/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_charsample_mylibraryndkdemo_JniNdkDemo */

#ifndef _Included_com_charsample_mylibraryndkdemo_JniNdkDemo
#define _Included_com_charsample_mylibraryndkdemo_JniNdkDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_charsample_mylibraryndkdemo_JniNdkDemo
 * Method:    ndkDemo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_charsample_mylibraryndkdemo_JniNdkDemo_ndkDemo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
